### ISSUE TITLE
Compile is failing

### ISSUE THREAD

**Issue by tkoop** [tkoop/berean-readers-bible-pwa#17]
/var/www/bible.timkoop.com/compile.js:47
		chapterHTML = chapterHTML.replaceAll('face="Tahoma, serif"', "")
		                          ^

TypeError: chapterHTML.replaceAll is not a function
    at parseHTML (/var/www/bible.timkoop.com/compile.js:47:29)

**Comment by jkoop** [comment]
`str.replaceAll()` requires node 15. What version are you running?
